#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    firstTierLeft,  sensorPotentiometer)
#pragma config(Sensor, in2,    secondTier,     sensorPotentiometer)
#pragma config(Sensor, in3,    leftLight,      sensorLineFollower)
#pragma config(Sensor, in4,    rightLight,     sensorLineFollower)
#pragma config(Sensor, in5,    backLight,      sensorLineFollower)
#pragma config(Sensor, dgtl3,  led,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, bumperRight,    sensorTouch)
#pragma config(Sensor, dgtl11, bumperLeft,     sensorTouch)
#pragma config(Sensor, I2C_1,  leftBack,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  rightBack,      sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           leftBack,      tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port2,           leftMiddle,    tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           leftFront,     tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port4,           firstTierLeft, tmotorVex393, openLoop)
#pragma config(Motor,  port5,           secondTier,    tmotorVex393, openLoop)
#pragma config(Motor,  port6,           intakeRollers, tmotorVex269, openLoop)
#pragma config(Motor,  port7,           firstTierRight, tmotorVex393, openLoop)
#pragma config(Motor,  port8,           rightFront,    tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port9,           rightMiddle,   tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port10,          rightBack,     tmotorVex393HighSpeed, openLoop, reversed, encoder, encoderPort, I2C_2, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////
int programs = 0;
task LED()
{

	while(true)
	{

		for(int i = 0;i<=programs;i++)
		{
			SensorValue[led]=1;
			wait1Msec(300);
			SensorValue[led]=0;
			wait1Msec(300);
		}

		wait1Msec(1000);
	}
}


void pre_auton()
{
	StartTask(LED);

	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;
	bool old1= false;
	bool pressed1;
	bool old2=false;
	bool pressed2;
	while(true)
	{
		if(SensorValue[bumperLeft]==1)
		{
			pressed1 = true;
		}
		else{
			pressed1 = false;
		}

		if(SensorValue[bumperRight]==1)
		{
			pressed2 = true;
		}
		else{
			pressed2 = false;
		}

		if(!old1&&pressed1)
		{
			if(programs==2)
			{
				programs = 0;
			}
			else{

				programs++;
			}
		}
		else if(!old2&&pressed2)
		{
			if(programs == 0)
			{
				programs=2;
			}
			else{
				programs--;
			}
		}
			old1 = pressed1;
			old2 = pressed2;
			wait10Msec(30);
		}


		// All activities that occur before the competition starts
		// Example: clearing encoders, setting servo  positions, ...
	}

	/////////////////////////////////////////////////////////////////////////////////////////
	//
	//                                 Autonomous Task
	//
	// This task is used to control your robot during the autonomous phase of a VEX Competition.
	// You must modify the code to add your own robot specific commands here.
	//
	/////////////////////////////////////////////////////////////////////////////////////////

	task autonomous()
	{
		// .....................................................................................
		// Insert user code here.
		// .....................................................................................

		if(programs ==0)
		{
		}
		else if(programs ==1)
		{
		}
		else if(programs ==2)
		{
		}
	}

	/////////////////////////////////////////////////////////////////////////////////////////
	//
	//                                 User Control Task
	//
	// This task is used to control your robot during the user control phase of a VEX Competition.
	// You must modify the code to add your own robot specific commands here.
	//
	/////////////////////////////////////////////////////////////////////////////////////////

	task usercontrol()
	{
		// User control code here, inside the loop

		while (true)
		{
			// This is the main execution loop for the user control program. Each time through the loop
			// your program should update motor + servo values based on feedback from the joysticks.

			// .....................................................................................
			// Insert user code here. This is where you use the joystick values to update your motors, etc.
			// .....................................................................................

			UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.
		}
	}
