#pragma config(Sensor, in1,    firstTierLeft,  sensorPotentiometer)
#pragma config(Sensor, in2,    secondTier,     sensorPotentiometer)
#pragma config(Sensor, in3,    leftLight,      sensorLineFollower)
#pragma config(Sensor, in4,    rightLight,     sensorLineFollower)
#pragma config(Sensor, in5,    backLight,      sensorLineFollower)
#pragma config(Sensor, dgtl3,  led,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  backRight,      sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  backLeft,       sensorQuadEncoder)
#pragma config(Sensor, dgtl10, bumperRight,    sensorTouch)
#pragma config(Sensor, dgtl11, bumperLeft,     sensorTouch)
#pragma config(Motor,  port1,           leftBack,      tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port2,           leftMiddle,    tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           leftFront,     tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port4,           firstTierLeft, tmotorVex393, openLoop)
#pragma config(Motor,  port5,           secondTier,    tmotorVex393, openLoop)
#pragma config(Motor,  port6,           intakeRollers, tmotorVex269, openLoop)
#pragma config(Motor,  port7,           firstTierRight, tmotorVex393, openLoop)
#pragma config(Motor,  port8,           rightFront,    tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port9,           rightMiddle,   tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port10,          rightBack,     tmotorVex393HighSpeed, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "FnLibSingaporeVex2013.h";

task main()
{
	/*Mid Right*/
	StartTask(intakeStart);
	ClearTimer(T4);
	intake = 1;
	moveSecondTierUp(127,450);
	moveSecondTierDown(127,50);
	motor[secondTier]=-127;
	wait10Msec(50);
	motor[secondTier]=0;
	moveStraightDistance(100,50);
	stopPid(0.6,0.3);
	intake = 0;
	moveStraightDistance(127,1800);
	stopPid(0.6,0.3);
	moveFirstTierUp(127,1200);
	motor[firstTierLeft]=20;
	motor[firstTierRight]=20;
	moveStraightDistance(127,200);
	stopPid(0.6,0.3);
	intake = -1;
	wait10Msec(300);
	intake = 0;
	moveStraightDistance(-127,200);
	stopPid(0.6,0.3);
	moveFirstTierDown(127,20);
	turnLeft(127,70);
	moveStraightDistance(-127,1500);
	while(SensorValue[bumperLeft]==0)
	{
	}
	moveStraightDistance(127,100);
	pushBridge(80,900);
	moveStraightDistance(100,200);
	moveStraightDistance(-100,420);
	stopPid(0.6,0.3);
	while(SensorValue[bumperLeft]==0)
	{
	}
	moveStraightDistance(100,300);
	stopPid(0.6,0.3);
	alignFoward(100);
	turnLeft(127,250);
	moveFirstTierUp(127,900);
	moveStraightDistance(100,800);
	stopPid(0.6,0.3);
	stopLift();
	moveStraightDistance(-100,100);
	stopPid(0.6,0.3);
}
